org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
CLERK_PUBLISHABLE_KEY=pk_test_c2hhcmluZy1pZ3VhbmEtNTguY2xlcmsuYWNjb3VudHMuZGV2JA
FIREBASE_TOKEN_BRIDGE_URL=https://portico-firebase-bridge.vercel.app/api/firebase-token
